spring:
  datasource:
    username: ${vcap.services.kkkkk.credentials.username}
    url: ${vcap.services.kkkkk.credentials.jdbcUrl}
    password: ${vcap.services.kkkkk.credentials.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true


server:
  port: 0
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    non-secure-port: 80
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${random.value}}

---
eureka:
  client:
    service-url:
      defaultZone: ${vcap.services.eurekaservice.credentials.uri}/eureka/
---
spring:
  cloud:
    config:
      discovery:
        service-id: CONFIGSERVER-SK