spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:32769/contacts
    password: admin

  jpa:
    show-sql: true
  cloud:
    config:

      discovery:
        enabled: true
        service-id:
---
spring:
  cloud:
    config:
      discovery:
        service-id: CONFIGSERVER-SK


server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/