spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:32773/contacts
    username: root
    password: admin
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

backend-service-a:
  message: 'This is the fresh message'