spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:32773/contacts
    username: root
    password: admin
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest

backend-service-a:
  message: 'This is the message-2'