spring:
  cloud:
    config:
      discovery:
        service-id: CONFIGSERVER-SK

---

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service-sk
          uri:  lb://CUSTOMER-SERVICE-SK
          predicates:
            - Path= /customer/**
          filters:
            - RewritePath=/customer/(?<segment>.*), /$\{segment}
