spring:
  datasource:
    username: b1f01b9cf59412
    url: jdbc:mysql://us-cdbr-iron-east-02.cleardb.net/ad_fffabff6d0e3adf
    password: bffa801d

  jpa:
    show-sql: true




server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/