spring:
  datasource:
    username: ${vcap.services.oracleservice.credentials.username}
    url: ${vcap.services.oracleservice.credentials.url}
    password: ${vcap.services.oracleservice.credentials.password}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true


server:
  port: 0
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${random.value}}
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80

---
eureka:
  client:
    service-url:
      defaultZone: ${vcap.services.eurekaservice.credentials.uri}/eureka/
---
spring:
  cloud:
    config:
      uri: http://configDownload